name: Trivy Test

on:
  workflow_dispatch:  
  
jobs:
  trivy-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug workspace
        run: |
          echo "PWD = $(pwd)"
          echo "Liste des fichiers à la racine :"
          ls -la
          echo "Liste récursive :"
          ls -R

      - name: Build Docker image
        run: |
          docker build -t netwatch-trivy-test:${{ github.sha }} -f Dockerfile .
